CREATE TABLE FPproduct(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    image VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    stock INT DEFAULT 0 CHECK (stock >=0),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);